// This file was autogenerated by calcdeps.js
goog.addDependency("../../src/binarydata.js", ["fontloader.BinaryData"], []);
goog.addDependency("../../src/cssvalue.js", ["fontloader.CssValue"], ["fontloader.util","fontloader.UnicodeRange","fontloader.Url"]);
goog.addDependency("../../src/debug.js", ["debug"], []);
goog.addDependency("../../src/eventhandler.js", ["fontloader.EventHandler"], []);
goog.addDependency("../../src/fontface.js", ["fontloader.FontFace"], ["fontloader.FontFaceLoadStatus","fontloader.FontFaceObserver","fontloader.CssValue","fontloader.UnicodeRange","fontloader.util"]);
goog.addDependency("../../src/fontfacedescriptors.js", ["fontloader.FontFaceDescriptors"], []);
goog.addDependency("../../src/fontfaceloadstatus.js", ["fontloader.FontFaceLoadStatus"], []);
goog.addDependency("../../src/fontfaceobserver.js", ["fontloader.FontFaceObserver"], ["fontloader.Ruler","fontloader.util"]);
goog.addDependency("../../src/fontfaceset.js", ["fontloader.FontFaceSet"], ["fontloader.FontFaceSetLoadStatus","fontloader.FontFaceLoadStatus","fontloader.EventHandler","fontloader.CssValue","fontloader.UnicodeRange"]);
goog.addDependency("../../src/fontfacesetloadstatus.js", ["fontloader.FontFaceSetLoadStatus"], []);
goog.addDependency("../../src/polyfill.js", ["fontloader"], ["fontloader.FontFace","fontloader.FontFaceSet"]);
goog.addDependency("../../src/range.js", ["fontloader.Range"], []);
goog.addDependency("../../src/ruler.js", ["fontloader.Ruler"], ["fontloader.util","fontloader.CssValue"]);
goog.addDependency("../../src/unicoderange.js", ["fontloader.UnicodeRange"], ["fontloader.Range"]);
goog.addDependency("../../src/url.js", ["fontloader.Url"], []);
goog.addDependency("../../src/util.js", ["fontloader.util"], []);
