// This file was autogenerated by calcdeps.js
goog.addDependency("../../src/cssfontloadevent.js", ["fontloader.CSSFontFaceLoadEvent"], []);
goog.addDependency("../../src/cssvalue.js", ["fontloader.CSSValue"], ["fontloader.util"]);
goog.addDependency("../../src/debug.js", ["debug"], []);
goog.addDependency("../../src/eventhandler.js", ["fontloader.EventHandler"], []);
goog.addDependency("../../src/fontloader.js", ["fontloader"], ["fontloader.CSSValue","fontloader.FontWatcher","fontloader.util"]);
goog.addDependency("../../src/fontsreadycallback.js", ["fontloader.FontsReadyCallback"], []);
goog.addDependency("../../src/fontwatcher.js", ["fontloader.FontWatcher"], ["fontloader.Ruler","fontloader.util"]);
goog.addDependency("../../src/loadfontparameters.js", ["fontloader.LoadFontParameters"], []);
goog.addDependency("../../src/ruler.js", ["fontloader.Ruler"], ["fontloader.util","fontloader.CSSValue"]);
goog.addDependency("../../src/util.js", ["fontloader.util"], []);
